DROP TABLE IF EXISTS mouvement;
DROP TABLE IF EXISTS projet;

-- CREATION ET INITIALISATION DE LA TABLE projet 
CREATE TABLE projet (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(50) NOT NULL,
    description_projet VARCHAR(2000),
    budget DECIMAL(15,2) NOT NULL CHECK (budget >= 0),
    date_debut DATE NOT NULL,
    date_fin DATE NOT NULL,
    statut VARCHAR(10) NOT NULL DEFAULT 'EN_COURS' CHECK (statut IN ('EN_COURS', 'TERMINE'))
 );
-- INITIALISATION DE LA TABLE projet AVEC DES DONNEES DE TEST
INSERT INTO projet (nom, description_projet, budget, date_debut, date_fin, statut)
VALUES
    ('Communicus', 'TEST: plateforme de communication interne pour equipes', 5000.00, '2026-01-01', '2026-12-31', 'EN_COURS'),
    ('Optimus', 'TEST: outils et process pour optimiser le cycle de dev', 12000.00, '2026-02-01', '2026-11-30', 'EN_COURS'),
    ('Networkus', NULL, 8000.00, '2026-03-01', '2026-10-15', 'EN_COURS'),
    ('Atlas', 'TEST: refonte infrastructure et migration data', 15000.00, '2025-05-01', '2026-02-28', 'TERMINE'),
    ('Helios', 'TEST: creation de portail clients et API', 20000.00, '2026-04-15', '2026-12-31', 'EN_COURS'),
    ('Aurora', NULL, 7500.00, '2026-06-01', '2026-12-20', 'EN_COURS'),
    ('Borealis', 'TEST: campagne marketing digital et analytics', 3000.00, '2026-07-01', '2027-01-31', 'EN_COURS'),
    ('Titan', 'TEST: proof-of-concept lourd et optimisation perf', 50000.00, '2025-01-10', '2025-12-31', 'TERMINE'),
    ('Mercury', NULL, 9500.00, '2026-05-20', '2027-01-15', 'EN_COURS'),
    ('Vega', 'TEST: prototype UI/UX et tests utilisateurs', 4200.00, '2026-08-01', '2027-02-28', 'EN_COURS');


-- CREATION ET INITIALISATION DE LA TABLE mouvement 
CREATE TABLE mouvement (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(50),
    libelle VARCHAR(500) NOT NULL,
    type_mouvement VARCHAR(10) NOT NULL CHECK (type_mouvement IN ('ENTREE', 'SORTIE')),
    montant DECIMAL(15,2) NOT NULL CHECK(montant>0),
    date_mouvement DATE NOT NULL,
    description_mouvement VARCHAR(2000),
    projet_id INT NOT NULL,
    CONSTRAINT fk_mouv_projet FOREIGN KEY (projet_id) REFERENCES projet (id)
 );
-- INITIALISATION DE LA TABLE mouvement AVEC DES DONNEES DE TEST
INSERT INTO mouvement (nom, libelle, type_mouvement, montant, date_mouvement, description_mouvement, projet_id)
VALUES
    ('apport_initial', 'TEST: apport initial projet Communicus', 'ENTREE', 5000.00, '2026-01-02', 'TEST: financement seed', 1),
    ('achat_serveurs', 'TEST: achat serveurs pour infra', 'SORTIE', 1200.00, '2026-01-15', NULL, 1),
    (NULL, 'TEST: prestation conseil optimisation', 'ENTREE', 2500.00, '2026-02-20', 'TEST: financement additionnel', 2),
    ('facture_conseil', 'TEST: facture conseil Optimus', 'SORTIE', 800.00, '2026-02-25', NULL, 2),
    ('subvention', 'TEST: subvention publique', 'ENTREE', 8000.00, '2026-03-10', 'TEST: subvention projet Networkus', 3),
    ('licences', 'TEST: licences logicielles annuelles', 'SORTIE', 1500.00, '2026-03-25', NULL, 3),
    ('paiement_client', 'TEST: reglement client final', 'ENTREE', 15000.00, '2026-02-28', 'TEST: paiement projet Atlas', 4),
    ('remboursement', 'TEST: remboursement frais Atlas', 'SORTIE', 2000.00, '2026-02-10', NULL, 4),
    ('externalisation', 'TEST: sous-traitance dev', 'SORTIE', 4000.00, '2026-05-10', 'TEST: depense sous-traitant', 5),
    ('bonus_performance', 'TEST: bonus performance Helios', 'ENTREE', 5000.00, '2026-05-25', NULL, 5),
    ('partenariat', 'TEST: apport partenaire strategic', 'ENTREE', 10000.00, '2026-06-05', 'TEST: financement Aurora', 6),
    ('achat_materiel', 'TEST: achat materiel Aurora', 'SORTIE', 2500.00, '2026-06-15', NULL, 6),
    ('budget_campagne', 'TEST: budget initial campagne', 'ENTREE', 3500.00, '2026-07-01', 'TEST: financement campagne Borealis', 7),
    ('campagne_pub', 'TEST: achat media campagne', 'SORTIE', 900.00, '2026-07-15', NULL, 7),
    ('revision_vega', 'TEST: revision audit UI/UX', 'ENTREE', 2000.00, '2026-08-10', NULL, 10),
    ('tests_utilisateurs', 'TEST: cout tests utilisateurs', 'SORTIE', 1200.00, '2026-08-25', 'TEST: frais tests Vega', 10),
    ('integration_frais', 'TEST: frais d integration API tierce', 'SORTIE', 600.00, '2026-06-20', NULL, 9),
    ('avance_mercury', 'TEST: avance financement Mercury', 'ENTREE', 1200.00, '2026-06-01', 'TEST: versement initial', 9);

-- CALCUL DU TOTAL DES ENTREES 
SELECT SUM(montant) AS total_entrees
FROM mouvement
WHERE type_mouvement = 'ENTREE';

-- CALCUL DU TOTAL DES SORTIES
SELECT SUM(montant) AS total_sorties
FROM mouvement
WHERE type_mouvement = 'SORTIE';