DROP TABLE IF EXISTS mouvement;
DROP TABLE IF EXISTS projet;

-- CREATION ET INITIALISATION DE LA TABLE projet 
CREATE TABLE projet (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(50) NOT NULL,
    description_projet VARCHAR(500) NOT NULL,
    budget DECIMAL(15,2) NOT NULL CHECK (budget >= 0),
    date_debut DATE NOT NULL,
    date_fin DATE NULL,
    statut VARCHAR(10) NOT NULL DEFAULT 'EN_COURS' CHECK (statut IN ('EN_COURS', 'TERMINE'))
 );

INSERT INTO projet (nom, description_projet, budget, date_debut, date_fin, statut)
VALUES ('communicus', 'realisation de plateforme de communication entre collegues', 44.34, '2026-01-01', NULL, 'EN_COURS'),
    ('optimus', 'mise en place des outils pour optimiser le developpement', 100.00, '2026-02-01', NULL, 'EN_COURS'),
    ('networkus', 'creation des espaces de networking en ligne pour directeurs et proprietaires des entreprises', 200.00, '2026-03-01', NULL, 'EN_COURS');


-- CREATION ET INITIALISATION DE LA TABLE mouvement 
CREATE TABLE mouvement (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(50) NOT NULL,
    libelle VARCHAR(500) NOT NULL,
    type_mouvement VARCHAR(10) NOT NULL CHECK (type_mouvement IN ('ENTREE', 'SORTIE')),
    montant DECIMAL(15,2) NOT NULL,
    date_mouvement DATE NOT NULL,
    description_mouvement VARCHAR(500) NOT NULL,
    projet_id INT NOT NULL,
    CONSTRAINT fk_mouv_projet FOREIGN KEY (projet_id) REFERENCES projet (id)
 );
-- CREATE INDEX idx_mouv_projet ON mouvement (projet_id);

INSERT INTO mouvement (nom, libelle, type_mouvement, montant, date_mouvement, description_mouvement, projet_id)
VALUES ('financement1', 'libelle1', 'ENTREE', 100.00, '2026-01-02', 'description1', 1),
       ('depense pour serveurs', 'libelle2', 'SORTIE', 50.00, '2026-03-03', 'description2', 1);
